### ISSUE TITLE
[MPAEU] Species distribution models

### ISSUE THREAD

**Issue by silasprincipe** [iobis/mpaeu_sdm#1]
# Phase 1 - establishing the framework

The framework was successfully established and applied with a number of species. Now, we are running the models for the remaining groups.

# Phase 2 - improvements

Several points needs to be improved:

- [x] Speed up Maxent algorithm
- [x] Test ensemble of models
- [x] Improve running time
- [x] Establish better control for overfitting (!)
- [x] Include spatial bias detection
- [ ] Include spatial bias treatments (!)
- [x] Assess if Precision Recall Gain curve is correctly working (also, revise metrics)
- [x] Establish codes for binarization of models
- [x] Add code to assess variable importance (!!!!)

Also need to try using GEE for the modeling.

# Phase 3 - running definitive models

As soon as the problems are solved, run the definitive models

# Phase 4 - establish an auto-update system

**Comment by silasprincipe** [comment]
Spatial bias still to be solved.
